# draft, work on permissions for glee files/folders
version: '3'

services:
  glee:
    build:
      context: .
      dockerfile_inline: |
        FROM asyncapi/cli
        USER root
        RUN asyncapi new glee --name=tutorial --template tutorial && \
            cd tutorial && \
            npm install
        ENTRYPOINT 
    volumes:
      - ${PWD}:/app/tutorial 
    networks:
      - default
    user: root # can we stick to default user and have glee file/folders editable by local user?
    entrypoint: []
    working_dir: /app/tutorial
    command: sleep infinity
   
networks:
  default: {}