name: Update latest Glee documentation in the website

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/pages/*.md'

jobs:
  Make-PR:
    name: Make PR on website repository with updated latest Glee documentation
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v3
        with:
          path: glee
      - name: Checkout Another repository
        uses: actions/checkout@v3
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
      - name: Config git
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
      - name: Create branch
        working-directory: ./website
        run: |
          git checkout -b update-glee-docs-${{ github.sha }}
      - name: Copy glee folder from Current Repo to Another
        working-directory: ./website
        run: |
          rm -r ./markdown/docs/tools/glee
          mkdir -p ./markdown/docs/tools/glee      
          printf "%s\ntitle: Glee\nweight: 06\n%s" "---" "---"> ../glee/docs/_section.md
          mv ../glee/docs/pages/*.md ./markdown/docs/tools/glee
      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(glee): update latest glee docs"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/website
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "docs(glee): update latest glee documentation" --body "Updated glee documentation is available and this PR introduces update to glee folder on the website" --head "update-glee-docs-${{ github.sha }}"
